package generator

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/Loschcode/protoc-gen-ai-tools/internal/annotations"
)

// AliasField describes a field that should be aliased for the LLM.
type AliasField struct {
	FieldName   string // JSON field name (e.g. "link_id", "id")
	AliasPrefix string // prefix for aliases (e.g. "link", "step")
}

// ToolInfo holds the data for a single AI agent tool.
type ToolInfo struct {
	VarName        string
	Name           string
	Description    string
	Strict         bool
	Schema         json.RawMessage
	AutoExecute    bool
	ServiceName    string
	MethodName     string
	InputTypeName  string
	OutputTypeName string
	GoImportPath   string
	AliasFields    []AliasField // fields that need alias resolution
	OutputPrefix   string       // prefix for new UUIDs in responses (from "id" field)
}

// Collector gathers annotated RPCs across proto files.
type Collector struct {
	tools []ToolInfo
}

// NewCollector creates a new tool collector.
func NewCollector() *Collector {
	return &Collector{}
}

// CollectFile processes a single proto file for rpc_tool annotations.
func (c *Collector) CollectFile(file *protogen.File) {
	for _, svc := range file.Services {
		for _, method := range svc.Methods {
			td, ok := annotations.ToolFromMethod(method.Desc)
			if !ok {
				continue
			}

			sg := NewSchemaGenerator(td.Strict)
			schemaMap := sg.Generate(method.Input.Desc)

			schemaJSON, err := json.Marshal(schemaMap)
			if err != nil {
				continue
			}

			// Collect alias fields from the request message
			var aliasFields []AliasField
			var outputPrefix string
			fields := method.Input.Desc.Fields()
			for i := 0; i < fields.Len(); i++ {
				f := fields.Get(i)
				opts := annotations.GetToolFieldOpts(f)
				if opts.AliasPrefix != "" {
					aliasFields = append(aliasFields, AliasField{
						FieldName:   string(f.Name()),
						AliasPrefix: opts.AliasPrefix,
					})
					// The "id" field (not "link_id", "step_id") is the entity
					// being created/updated — use its prefix for new UUIDs in responses.
					if string(f.Name()) == "id" {
						outputPrefix = opts.AliasPrefix
					}
				}
			}
			// Fallback: if no "id" field, use the first alias prefix
			if outputPrefix == "" && len(aliasFields) > 0 {
				outputPrefix = aliasFields[0].AliasPrefix
			}

			c.tools = append(c.tools, ToolInfo{
				VarName:        snakeToPascal(td.Name),
				Name:           td.Name,
				Description:    td.Description,
				Strict:         td.Strict,
				Schema:         schemaJSON,
				AutoExecute:    td.AutoExecute,
				ServiceName:    string(method.Desc.Parent().Name()),
				MethodName:     string(method.Desc.Name()),
				InputTypeName:  method.Input.GoIdent.GoName,
				OutputTypeName: method.Output.GoIdent.GoName,
				GoImportPath:   string(method.Input.GoIdent.GoImportPath),
				AliasFields:    aliasFields,
				OutputPrefix:   outputPrefix,
			})
		}
	}
}

// Generate produces Go source code with all collected tool definitions.
// Returns empty string if no tools were collected.
func (c *Collector) Generate() string {
	if len(c.tools) == 0 {
		return ""
	}

	// Sort tools by name for deterministic output.
	sort.Slice(c.tools, func(i, j int) bool {
		return c.tools[i].Name < c.tools[j].Name
	})

	// Collect auto_execute tools and their import paths.
	var autoTools []ToolInfo
	importPaths := make(map[string]bool)
	for _, t := range c.tools {
		if t.AutoExecute {
			autoTools = append(autoTools, t)
			importPaths[t.GoImportPath] = true
		}
	}
	hasExecutors := len(autoTools) > 0

	// Check if any tool has alias fields.
	hasAliases := false
	for _, t := range c.tools {
		if len(t.AliasFields) > 0 {
			hasAliases = true
			break
		}
	}

	var b strings.Builder

	b.WriteString("// Code generated by protoc-gen-ai-tools. DO NOT EDIT.\n")
	b.WriteString("package gentools\n\n")

	// Imports block.
	if hasExecutors {
		b.WriteString("import (\n")
		b.WriteString("\t\"context\"\n")
		b.WriteString("\t\"encoding/json\"\n")
		b.WriteString("\t\"fmt\"\n")
		if hasAliases {
			b.WriteString("\t\"regexp\"\n")
			b.WriteString("\t\"strings\"\n")
			b.WriteString("\t\"sync\"\n")
		}
		b.WriteString("\n")
		b.WriteString("\t\"google.golang.org/grpc\"\n")
		b.WriteString("\t\"google.golang.org/protobuf/encoding/protojson\"\n")
		b.WriteString("\n")

		// Deduplicate and sort import paths for deterministic output.
		var paths []string
		for p := range importPaths {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			b.WriteString(fmt.Sprintf("\tpb %q\n", p))
		}
		b.WriteString(")\n\n")
	} else if hasAliases {
		b.WriteString("import (\n")
		b.WriteString("\t\"encoding/json\"\n")
		b.WriteString("\t\"fmt\"\n")
		b.WriteString("\t\"regexp\"\n")
		b.WriteString("\t\"strings\"\n")
		b.WriteString("\t\"sync\"\n")
		b.WriteString(")\n\n")
	} else {
		b.WriteString("import \"encoding/json\"\n\n")
	}

	b.WriteString("// AgentTool is a library-agnostic AI agent tool definition.\n")
	b.WriteString("type AgentTool struct {\n")
	b.WriteString("\tName        string\n")
	b.WriteString("\tDescription string\n")
	b.WriteString("\tStrict      bool\n")
	b.WriteString("\tParameters  json.RawMessage\n")
	b.WriteString("}\n")

	// Generate individual tool variables.
	for _, t := range c.tools {
		b.WriteString("\n")
		b.WriteString(fmt.Sprintf("var %s = AgentTool{\n", t.VarName))
		b.WriteString(fmt.Sprintf("\tName:        %q,\n", t.Name))
		b.WriteString(fmt.Sprintf("\tDescription: %q,\n", t.Description))
		b.WriteString(fmt.Sprintf("\tStrict:      %t,\n", t.Strict))
		b.WriteString(fmt.Sprintf("\tParameters:  json.RawMessage(%q),\n", string(t.Schema)))
		b.WriteString("}\n")
	}

	// Generate AllTools function.
	b.WriteString("\n// AllTools returns all generated tool definitions.\n")
	b.WriteString("func AllTools() []AgentTool {\n")
	b.WriteString("\treturn []AgentTool{\n")
	for _, t := range c.tools {
		b.WriteString(fmt.Sprintf("\t\t%s,\n", t.VarName))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	// Generate AliasManager if any tool has alias fields.
	if hasAliases {
		c.generateAliasManager(&b)
	}

	// Generate executor code if any tools have auto_execute.
	if hasExecutors {
		// Generate toolAliasPrefixes map if aliases exist.
		if hasAliases {
			c.generateToolAliasPrefixes(&b, autoTools)
		}

		b.WriteString("\n// Executor provides auto-generated tool executors backed by gRPC.\n")
		b.WriteString("type Executor struct {\n")
		b.WriteString("\tconn grpc.ClientConnInterface\n")
		if hasAliases {
			b.WriteString("\taliases *AliasManager\n")
		}
		b.WriteString("}\n")

		b.WriteString("\n// NewExecutor creates an Executor with the given gRPC connection.\n")
		b.WriteString("func NewExecutor(conn grpc.ClientConnInterface) *Executor {\n")
		if hasAliases {
			b.WriteString("\treturn &Executor{conn: conn, aliases: NewAliasManager()}\n")
		} else {
			b.WriteString("\treturn &Executor{conn: conn}\n")
		}
		b.WriteString("}\n")

		if hasAliases {
			b.WriteString("\n// GetAliasManager returns the alias manager for external use (e.g. manual tools).\n")
			b.WriteString("func (e *Executor) GetAliasManager() *AliasManager {\n")
			b.WriteString("\treturn e.aliases\n")
			b.WriteString("}\n")
		}

		// Generate individual executor methods.
		for _, t := range autoTools {
			funcName := "Execute" + snakeToPascal(t.Name)
			b.WriteString(fmt.Sprintf("\n// %s calls %s.%s via gRPC.\n", funcName, t.ServiceName, t.MethodName))
			b.WriteString(fmt.Sprintf("func (e *Executor) %s(ctx context.Context, argsJSON string) (string, error) {\n", funcName))
			if hasAliases {
				b.WriteString(fmt.Sprintf("\targsJSON = e.aliases.ResolveJSON(%q, argsJSON)\n", t.Name))
			}
			b.WriteString(fmt.Sprintf("\tvar req pb.%s\n", t.InputTypeName))
			b.WriteString("\topts := protojson.UnmarshalOptions{DiscardUnknown: true}\n")
			b.WriteString("\tif err := opts.Unmarshal([]byte(argsJSON), &req); err != nil {\n")
			b.WriteString("\t\treturn \"\", fmt.Errorf(\"failed to parse arguments: %w\", err)\n")
			b.WriteString("\t}\n")
			b.WriteString(fmt.Sprintf("\tclient := pb.New%sClient(e.conn)\n", t.ServiceName))
			b.WriteString(fmt.Sprintf("\tresp, err := client.%s(ctx, &req)\n", t.MethodName))
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn \"\", err\n")
			b.WriteString("\t}\n")
			b.WriteString("\tmopts := protojson.MarshalOptions{EmitUnpopulated: false}\n")
			b.WriteString("\tout, err := mopts.Marshal(resp)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn \"\", fmt.Errorf(\"failed to marshal response: %w\", err)\n")
			b.WriteString("\t}\n")
			if hasAliases {
				b.WriteString(fmt.Sprintf("\tif prefix, ok := toolOutputPrefix[%q]; ok && prefix != \"\" {\n", t.Name))
				b.WriteString("\t\te.aliases.RegisterNewUUIDs(prefix, string(out))\n")
				b.WriteString("\t}\n")
				b.WriteString(fmt.Sprintf("\treturn e.aliases.AliasifyJSON(%q, string(out)), nil\n", t.Name))
			} else {
				b.WriteString("\treturn string(out), nil\n")
			}
			b.WriteString("}\n")
		}

		// Generate CanExecute method.
		b.WriteString("\n// CanExecute returns true if the given tool name has an auto-generated executor.\n")
		b.WriteString("func (e *Executor) CanExecute(toolName string) bool {\n")
		b.WriteString("\tswitch toolName {\n")
		for _, t := range autoTools {
			b.WriteString(fmt.Sprintf("\tcase %q:\n", t.Name))
			b.WriteString("\t\treturn true\n")
		}
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\treturn false\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n")

		// Generate Execute dispatcher method.
		b.WriteString("\n// Execute dispatches to the correct executor by tool name.\n")
		b.WriteString("func (e *Executor) Execute(ctx context.Context, toolName string, argsJSON string) (string, error) {\n")
		b.WriteString("\tswitch toolName {\n")
		for _, t := range autoTools {
			funcName := "Execute" + snakeToPascal(t.Name)
			b.WriteString(fmt.Sprintf("\tcase %q:\n", t.Name))
			b.WriteString(fmt.Sprintf("\t\treturn e.%s(ctx, argsJSON)\n", funcName))
		}
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\treturn \"\", fmt.Errorf(\"no auto-executor for tool: %s\", toolName)\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n")
	}

	return strings.TrimRight(b.String(), "\n")
}

// generateAliasManager writes the AliasManager struct and methods.
func (c *Collector) generateAliasManager(b *strings.Builder) {
	b.WriteString("\n// AliasManager maps UUIDs to human-readable aliases and back.\n")
	b.WriteString("// The LLM never sees raw UUIDs — only aliases like \"link-1\", \"step-2\".\n")
	b.WriteString("// Thread-safe for concurrent use within a single conversation.\n")
	b.WriteString("type AliasManager struct {\n")
	b.WriteString("\tmu       sync.Mutex\n")
	b.WriteString("\tcounters map[string]int            // prefix → next counter\n")
	b.WriteString("\ttoAlias  map[string]string         // UUID → alias\n")
	b.WriteString("\ttoUUID   map[string]string         // alias → UUID\n")
	b.WriteString("}\n")

	b.WriteString("\n// NewAliasManager creates a new AliasManager.\n")
	b.WriteString("func NewAliasManager() *AliasManager {\n")
	b.WriteString("\treturn &AliasManager{\n")
	b.WriteString("\t\tcounters: make(map[string]int),\n")
	b.WriteString("\t\ttoAlias:  make(map[string]string),\n")
	b.WriteString("\t\ttoUUID:   make(map[string]string),\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	b.WriteString("\n// Register assigns an alias to a UUID. If the UUID already has an alias, returns it.\n")
	b.WriteString("func (am *AliasManager) Register(prefix string, uuid string) string {\n")
	b.WriteString("\tam.mu.Lock()\n")
	b.WriteString("\tdefer am.mu.Unlock()\n")
	b.WriteString("\tif alias, ok := am.toAlias[uuid]; ok {\n")
	b.WriteString("\t\treturn alias\n")
	b.WriteString("\t}\n")
	b.WriteString("\tam.counters[prefix]++\n")
	b.WriteString("\talias := fmt.Sprintf(\"%s-%d\", prefix, am.counters[prefix])\n")
	b.WriteString("\tam.toAlias[uuid] = alias\n")
	b.WriteString("\tam.toUUID[alias] = uuid\n")
	b.WriteString("\treturn alias\n")
	b.WriteString("}\n")

	b.WriteString("\n// ResolveAlias returns the UUID for an alias. If not found, returns the input unchanged.\n")
	b.WriteString("func (am *AliasManager) ResolveAlias(alias string) string {\n")
	b.WriteString("\tam.mu.Lock()\n")
	b.WriteString("\tdefer am.mu.Unlock()\n")
	b.WriteString("\tif uuid, ok := am.toUUID[alias]; ok {\n")
	b.WriteString("\t\treturn uuid\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn alias\n")
	b.WriteString("}\n")

	b.WriteString("\n// AliasifyJSON replaces UUID values with aliases in a JSON string.\n")
	b.WriteString("func (am *AliasManager) AliasifyJSON(toolName string, jsonStr string) string {\n")
	b.WriteString("\tam.mu.Lock()\n")
	b.WriteString("\tdefer am.mu.Unlock()\n")
	b.WriteString("\tfor uuid, alias := range am.toAlias {\n")
	b.WriteString("\t\tjsonStr = strings.ReplaceAll(jsonStr, uuid, alias)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn jsonStr\n")
	b.WriteString("}\n")

	b.WriteString("\n// ResolveJSON replaces alias values with UUIDs in a JSON string.\n")
	b.WriteString("func (am *AliasManager) ResolveJSON(toolName string, jsonStr string) string {\n")
	b.WriteString("\tam.mu.Lock()\n")
	b.WriteString("\tdefer am.mu.Unlock()\n")
	b.WriteString("\tfor alias, uuid := range am.toUUID {\n")
	b.WriteString("\t\tjsonStr = strings.ReplaceAll(jsonStr, alias, uuid)\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn jsonStr\n")
	b.WriteString("}\n")

	b.WriteString("\nvar uuidPattern = regexp.MustCompile(`[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}`)\n")

	b.WriteString("\n// RegisterNewUUIDs scans a JSON string for UUID patterns and registers any new ones.\n")
	b.WriteString("func (am *AliasManager) RegisterNewUUIDs(prefix string, jsonStr string) {\n")
	b.WriteString("\tfor _, uuid := range uuidPattern.FindAllString(jsonStr, -1) {\n")
	b.WriteString("\t\tam.Register(prefix, uuid)\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
}

// generateToolAliasPrefixes writes the toolAliasPrefixes map variable.
func (c *Collector) generateToolAliasPrefixes(b *strings.Builder, autoTools []ToolInfo) {
	// Collect output prefix per tool (prefix from the "id" field).
	hasEntries := false
	for _, t := range autoTools {
		if t.OutputPrefix != "" {
			hasEntries = true
			break
		}
	}

	if !hasEntries {
		return
	}

	b.WriteString("\n// toolOutputPrefix maps tool names to the single prefix used for registering\n")
	b.WriteString("// new UUIDs from responses. This is the prefix from the 'id' field (the entity\n")
	b.WriteString("// being created/updated), not from reference fields like 'link_id'.\n")
	b.WriteString("var toolOutputPrefix = map[string]string{\n")
	for _, t := range autoTools {
		if t.OutputPrefix != "" {
			b.WriteString(fmt.Sprintf("\t%q: %q,\n", t.Name, t.OutputPrefix))
		}
	}
	b.WriteString("}\n")
}

// snakeToPascal converts a snake_case string to PascalCase.
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			result.WriteString(part[1:])
		}
	}
	return result.String()
}
