package generator

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/Loschcode/protoc-gen-ai-tools/internal/annotations"
)

// ToolInfo holds the data for a single AI agent tool.
type ToolInfo struct {
	VarName        string
	Name           string
	Description    string
	Strict         bool
	Schema         json.RawMessage
	AutoExecute    bool
	ServiceName    string
	MethodName     string
	InputTypeName  string
	OutputTypeName string
	GoImportPath   string
}

// Collector gathers annotated RPCs across proto files.
type Collector struct {
	tools []ToolInfo
}

// NewCollector creates a new tool collector.
func NewCollector() *Collector {
	return &Collector{}
}

// CollectFile processes a single proto file for rpc_tool annotations.
func (c *Collector) CollectFile(file *protogen.File) {
	for _, svc := range file.Services {
		for _, method := range svc.Methods {
			td, ok := annotations.ToolFromMethod(method.Desc)
			if !ok {
				continue
			}

			sg := NewSchemaGenerator(td.Strict)
			schemaMap := sg.Generate(method.Input.Desc)

			schemaJSON, err := json.Marshal(schemaMap)
			if err != nil {
				continue
			}

			c.tools = append(c.tools, ToolInfo{
				VarName:        snakeToPascal(td.Name),
				Name:           td.Name,
				Description:    td.Description,
				Strict:         td.Strict,
				Schema:         schemaJSON,
				AutoExecute:    td.AutoExecute,
				ServiceName:    string(method.Desc.Parent().Name()),
				MethodName:     string(method.Desc.Name()),
				InputTypeName:  method.Input.GoIdent.GoName,
				OutputTypeName: method.Output.GoIdent.GoName,
				GoImportPath:   string(method.Input.GoIdent.GoImportPath),
			})
		}
	}
}

// Generate produces Go source code with all collected tool definitions.
// Returns empty string if no tools were collected.
func (c *Collector) Generate() string {
	if len(c.tools) == 0 {
		return ""
	}

	// Sort tools by name for deterministic output.
	sort.Slice(c.tools, func(i, j int) bool {
		return c.tools[i].Name < c.tools[j].Name
	})

	// Collect auto_execute tools and their import paths.
	var autoTools []ToolInfo
	importPaths := make(map[string]bool)
	for _, t := range c.tools {
		if t.AutoExecute {
			autoTools = append(autoTools, t)
			importPaths[t.GoImportPath] = true
		}
	}
	hasExecutors := len(autoTools) > 0

	var b strings.Builder

	b.WriteString("// Code generated by protoc-gen-ai-tools. DO NOT EDIT.\n")
	b.WriteString("package gentools\n\n")

	// Imports block.
	if hasExecutors {
		b.WriteString("import (\n")
		b.WriteString("\t\"context\"\n")
		b.WriteString("\t\"encoding/json\"\n")
		b.WriteString("\t\"fmt\"\n")
		b.WriteString("\n")
		b.WriteString("\t\"google.golang.org/grpc\"\n")
		b.WriteString("\t\"google.golang.org/protobuf/encoding/protojson\"\n")
		b.WriteString("\n")

		// Deduplicate and sort import paths for deterministic output.
		var paths []string
		for p := range importPaths {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		for _, p := range paths {
			b.WriteString(fmt.Sprintf("\tpb %q\n", p))
		}
		b.WriteString(")\n\n")
	} else {
		b.WriteString("import \"encoding/json\"\n\n")
	}

	b.WriteString("// AgentTool is a library-agnostic AI agent tool definition.\n")
	b.WriteString("type AgentTool struct {\n")
	b.WriteString("\tName        string\n")
	b.WriteString("\tDescription string\n")
	b.WriteString("\tStrict      bool\n")
	b.WriteString("\tParameters  json.RawMessage\n")
	b.WriteString("}\n")

	// Generate individual tool variables.
	for _, t := range c.tools {
		b.WriteString("\n")
		b.WriteString(fmt.Sprintf("var %s = AgentTool{\n", t.VarName))
		b.WriteString(fmt.Sprintf("\tName:        %q,\n", t.Name))
		b.WriteString(fmt.Sprintf("\tDescription: %q,\n", t.Description))
		b.WriteString(fmt.Sprintf("\tStrict:      %t,\n", t.Strict))
		b.WriteString(fmt.Sprintf("\tParameters:  json.RawMessage(%q),\n", string(t.Schema)))
		b.WriteString("}\n")
	}

	// Generate AllTools function.
	b.WriteString("\n// AllTools returns all generated tool definitions.\n")
	b.WriteString("func AllTools() []AgentTool {\n")
	b.WriteString("\treturn []AgentTool{\n")
	for _, t := range c.tools {
		b.WriteString(fmt.Sprintf("\t\t%s,\n", t.VarName))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	// Generate executor code if any tools have auto_execute.
	if hasExecutors {
		b.WriteString("\n// Executor provides auto-generated tool executors backed by gRPC.\n")
		b.WriteString("type Executor struct {\n")
		b.WriteString("\tconn grpc.ClientConnInterface\n")
		b.WriteString("}\n")

		b.WriteString("\n// NewExecutor creates an Executor with the given gRPC connection.\n")
		b.WriteString("func NewExecutor(conn grpc.ClientConnInterface) *Executor {\n")
		b.WriteString("\treturn &Executor{conn: conn}\n")
		b.WriteString("}\n")

		// Generate individual executor methods.
		for _, t := range autoTools {
			funcName := "Execute" + snakeToPascal(t.Name)
			b.WriteString(fmt.Sprintf("\n// %s calls %s.%s via gRPC.\n", funcName, t.ServiceName, t.MethodName))
			b.WriteString(fmt.Sprintf("func (e *Executor) %s(ctx context.Context, argsJSON string) (string, error) {\n", funcName))
			b.WriteString(fmt.Sprintf("\tvar req pb.%s\n", t.InputTypeName))
			b.WriteString("\topts := protojson.UnmarshalOptions{DiscardUnknown: true}\n")
			b.WriteString("\tif err := opts.Unmarshal([]byte(argsJSON), &req); err != nil {\n")
			b.WriteString("\t\treturn \"\", fmt.Errorf(\"failed to parse arguments: %w\", err)\n")
			b.WriteString("\t}\n")
			b.WriteString(fmt.Sprintf("\tclient := pb.New%sClient(e.conn)\n", t.ServiceName))
			b.WriteString(fmt.Sprintf("\tresp, err := client.%s(ctx, &req)\n", t.MethodName))
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn \"\", err\n")
			b.WriteString("\t}\n")
			b.WriteString("\tmopts := protojson.MarshalOptions{EmitUnpopulated: false}\n")
			b.WriteString("\tout, err := mopts.Marshal(resp)\n")
			b.WriteString("\tif err != nil {\n")
			b.WriteString("\t\treturn \"\", fmt.Errorf(\"failed to marshal response: %w\", err)\n")
			b.WriteString("\t}\n")
			b.WriteString("\treturn string(out), nil\n")
			b.WriteString("}\n")
		}

		// Generate CanExecute method.
		b.WriteString("\n// CanExecute returns true if the given tool name has an auto-generated executor.\n")
		b.WriteString("func (e *Executor) CanExecute(toolName string) bool {\n")
		b.WriteString("\tswitch toolName {\n")
		for _, t := range autoTools {
			b.WriteString(fmt.Sprintf("\tcase %q:\n", t.Name))
			b.WriteString("\t\treturn true\n")
		}
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\treturn false\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n")

		// Generate Execute dispatcher method.
		b.WriteString("\n// Execute dispatches to the correct executor by tool name.\n")
		b.WriteString("func (e *Executor) Execute(ctx context.Context, toolName string, argsJSON string) (string, error) {\n")
		b.WriteString("\tswitch toolName {\n")
		for _, t := range autoTools {
			funcName := "Execute" + snakeToPascal(t.Name)
			b.WriteString(fmt.Sprintf("\tcase %q:\n", t.Name))
			b.WriteString(fmt.Sprintf("\t\treturn e.%s(ctx, argsJSON)\n", funcName))
		}
		b.WriteString("\tdefault:\n")
		b.WriteString("\t\treturn \"\", fmt.Errorf(\"no auto-executor for tool: %s\", toolName)\n")
		b.WriteString("\t}\n")
		b.WriteString("}\n")
	}

	return strings.TrimRight(b.String(), "\n")
}

// snakeToPascal converts a snake_case string to PascalCase.
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			result.WriteString(part[1:])
		}
	}
	return result.String()
}
