package generator

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	"github.com/Loschcode/protoc-gen-ai-tools/internal/annotations"
)

// ToolInfo holds the data for a single AI agent tool.
type ToolInfo struct {
	VarName     string
	Name        string
	Description string
	Strict      bool
	Schema      json.RawMessage
}

// Collector gathers annotated RPCs across proto files.
type Collector struct {
	tools []ToolInfo
}

// NewCollector creates a new tool collector.
func NewCollector() *Collector {
	return &Collector{}
}

// CollectFile processes a single proto file for rpc_tool annotations.
func (c *Collector) CollectFile(file *protogen.File) {
	for _, svc := range file.Services {
		for _, method := range svc.Methods {
			td, ok := annotations.ToolFromMethod(method.Desc)
			if !ok {
				continue
			}

			sg := NewSchemaGenerator(td.Strict)
			schemaMap := sg.Generate(method.Input.Desc)

			schemaJSON, err := json.Marshal(schemaMap)
			if err != nil {
				continue
			}

			c.tools = append(c.tools, ToolInfo{
				VarName:     snakeToPascal(td.Name),
				Name:        td.Name,
				Description: td.Description,
				Strict:      td.Strict,
				Schema:      schemaJSON,
			})
		}
	}
}

// Generate produces Go source code with all collected tool definitions.
// Returns empty string if no tools were collected.
func (c *Collector) Generate() string {
	if len(c.tools) == 0 {
		return ""
	}

	// Sort tools by name for deterministic output.
	sort.Slice(c.tools, func(i, j int) bool {
		return c.tools[i].Name < c.tools[j].Name
	})

	var b strings.Builder

	b.WriteString("// Code generated by protoc-gen-ai-tools. DO NOT EDIT.\n")
	b.WriteString("package gentools\n\n")
	b.WriteString("import \"encoding/json\"\n\n")

	b.WriteString("// AgentTool is a library-agnostic AI agent tool definition.\n")
	b.WriteString("type AgentTool struct {\n")
	b.WriteString("\tName        string\n")
	b.WriteString("\tDescription string\n")
	b.WriteString("\tStrict      bool\n")
	b.WriteString("\tParameters  json.RawMessage\n")
	b.WriteString("}\n")

	// Generate individual tool variables.
	for _, t := range c.tools {
		b.WriteString("\n")
		b.WriteString(fmt.Sprintf("var %s = AgentTool{\n", t.VarName))
		b.WriteString(fmt.Sprintf("\tName:        %q,\n", t.Name))
		b.WriteString(fmt.Sprintf("\tDescription: %q,\n", t.Description))
		b.WriteString(fmt.Sprintf("\tStrict:      %t,\n", t.Strict))
		b.WriteString(fmt.Sprintf("\tParameters:  json.RawMessage(%q),\n", string(t.Schema)))
		b.WriteString("}\n")
	}

	// Generate AllTools function.
	b.WriteString("\n// AllTools returns all generated tool definitions.\n")
	b.WriteString("func AllTools() []AgentTool {\n")
	b.WriteString("\treturn []AgentTool{\n")
	for _, t := range c.tools {
		b.WriteString(fmt.Sprintf("\t\t%s,\n", t.VarName))
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return strings.TrimRight(b.String(), "\n")
}

// snakeToPascal converts a snake_case string to PascalCase.
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		result.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			result.WriteString(part[1:])
		}
	}
	return result.String()
}
