// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ai/tools/v1/annotations.proto

package ai_tools_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolDefinition describes an AI agent tool backed by an RPC method.
// The protoc-gen-ai-tools plugin uses this to generate Go AgentTool
// definitions with JSON Schema parameters derived from the request message.
type ToolDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tool name used by the AI agent (e.g. "page_themes_update").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Human-readable description shown to the LLM.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Whether to enforce strict parameter validation (additionalProperties: false).
	Strict bool `protobuf:"varint,3,opt,name=strict,proto3" json:"strict,omitempty"`
	// When true, generate an executor function that calls the gRPC service
	// directly (unmarshal args → call RPC → marshal response). Tools without
	// this flag only get the tool definition generated.
	AutoExecute   bool `protobuf:"varint,4,opt,name=auto_execute,json=autoExecute,proto3" json:"auto_execute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_proto_ai_tools_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_tools_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_proto_ai_tools_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *ToolDefinition) GetAutoExecute() bool {
	if x != nil {
		return x.AutoExecute
	}
	return false
}

var file_proto_ai_tools_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ToolDefinition)(nil),
		Field:         52104,
		Name:          "ai.tools.v1.rpc_tool",
		Tag:           "bytes,52104,opt,name=rpc_tool",
		Filename:      "proto/ai/tools/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional ai.tools.v1.ToolDefinition rpc_tool = 52104;
	E_RpcTool = &file_proto_ai_tools_v1_annotations_proto_extTypes[0]
)

var File_proto_ai_tools_v1_annotations_proto protoreflect.FileDescriptor

const file_proto_ai_tools_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"#proto/ai/tools/v1/annotations.proto\x12\vai.tools.v1\x1a google/protobuf/descriptor.proto\"\x81\x01\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06strict\x18\x03 \x01(\bR\x06strict\x12!\n" +
	"\fauto_execute\x18\x04 \x01(\bR\vautoExecute:X\n" +
	"\brpc_tool\x12\x1e.google.protobuf.MethodOptions\x18\x88\x97\x03 \x01(\v2\x1b.ai.tools.v1.ToolDefinitionR\arpcToolBBZ@github.com/Loschcode/protoc-gen-ai-tools/ai/tools/v1;ai_tools_v1b\x06proto3"

var (
	file_proto_ai_tools_v1_annotations_proto_rawDescOnce sync.Once
	file_proto_ai_tools_v1_annotations_proto_rawDescData []byte
)

func file_proto_ai_tools_v1_annotations_proto_rawDescGZIP() []byte {
	file_proto_ai_tools_v1_annotations_proto_rawDescOnce.Do(func() {
		file_proto_ai_tools_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_tools_v1_annotations_proto_rawDesc), len(file_proto_ai_tools_v1_annotations_proto_rawDesc)))
	})
	return file_proto_ai_tools_v1_annotations_proto_rawDescData
}

var file_proto_ai_tools_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_ai_tools_v1_annotations_proto_goTypes = []any{
	(*ToolDefinition)(nil),             // 0: ai.tools.v1.ToolDefinition
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_proto_ai_tools_v1_annotations_proto_depIdxs = []int32{
	1, // 0: ai.tools.v1.rpc_tool:extendee -> google.protobuf.MethodOptions
	0, // 1: ai.tools.v1.rpc_tool:type_name -> ai.tools.v1.ToolDefinition
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ai_tools_v1_annotations_proto_init() }
func file_proto_ai_tools_v1_annotations_proto_init() {
	if File_proto_ai_tools_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_tools_v1_annotations_proto_rawDesc), len(file_proto_ai_tools_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_proto_ai_tools_v1_annotations_proto_goTypes,
		DependencyIndexes: file_proto_ai_tools_v1_annotations_proto_depIdxs,
		MessageInfos:      file_proto_ai_tools_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_proto_ai_tools_v1_annotations_proto_extTypes,
	}.Build()
	File_proto_ai_tools_v1_annotations_proto = out.File
	file_proto_ai_tools_v1_annotations_proto_goTypes = nil
	file_proto_ai_tools_v1_annotations_proto_depIdxs = nil
}
